# baseURL = "http://example.org/"
# languageCode = "en-us"
# title = "My blog"
# theme = "ananke"

title = "muuuuuuuuuu blog"
baseURL = "https://muuuuuuuuu.github.io/Myproject2"
languageCode = "en-us"
theme = "ananke"
publishDir = "docs"
# themesDir = "../.."
# disqusShortname = YOURSHORTNAME

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/muuuuuuuuuu7"
  instagram = ""
  youtube = ""
  github = "https://github.com/muuuuuuuuuu"
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gulasu.jpg"
  recent_posts_number = 2
